-- 创建数据库
CREATE DATABASE IF NOT EXISTS paint;
USE paint;

-- 创建用户表
-- CREATE TABLE IF NOT EXISTS users (
--   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
--   username VARCHAR(100) UNIQUE NOT NULL,
--   password VARCHAR(255) NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   deleted_at TIMESTAMP NULL
-- );

-- -- 创建作品表
-- CREATE TABLE IF NOT EXISTS works (
--   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
--   user_id BIGINT UNSIGNED NOT NULL,
--   title VARCHAR(255) NOT NULL,
--   image VARCHAR(500),
--   content LONGTEXT,
--   author VARCHAR(100),
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   deleted_at TIMESTAMP NULL,
--   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- -- 创建评论表
-- CREATE TABLE IF NOT EXISTS comments (
--   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
--   work_id BIGINT UNSIGNED NOT NULL,
--   fromuser VARCHAR(100),
--   content LONGTEXT,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   deleted_at TIMESTAMP NULL,
--   FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE
-- );

-- 创建索引
-- CREATE INDEX idx_username ON users(username);
-- CREATE INDEX idx_user_id ON works(user_id);
-- CREATE INDEX idx_work_id ON comments(work_id);
