# dockerfile
FROM golang:1.25.4-alpine AS builder
RUN apk add --no-cache git
WORKDIR /Cloud_Gallery

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# 生成静态二进制，减小体积
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o main ./main.go

# 运行阶段使用 Alpine
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /Cloud_Gallery/main ./app
EXPOSE 8080
CMD ["./app"]
